import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarVisiteur from "@/components/NavbarVisiteur";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" data-theme="light">
      <body className={inter.className}>
        <div className="flex-wrap">
          <NavbarVisiteur></NavbarVisiteur>
          <div className="flex">{children}</div>
        </div>
      </body>
    </html>
  );
}
